import Head from 'next/head';
import { Fragment } from 'react';
import Layout from '../components/layout/Layout';
// import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <meta charset='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='./images/favicon-32x32.png'
        />
        <title>Frontend Mentor | E-commerce product page</title>
      </Head>
    </Fragment>
  );
}
